// seedEvents.js — real, hand-verified events only (the original placeholder
// EVENT_POOL demo rows without a real ticket link have been removed, since
// those fell back to a plain Google Maps link instead of a real source).
// host_user_id is implicitly NULL = editorial. date_text is kept as free
// text for now; see README for notes on moving to real Date values + a
// live source.

module.exports = [
  { title: "BACK TO THE CITY!! ft. AB-SOUL", venue: "New Town Mall, JHB", cat: "Music", price: "From R200", date_text: "Sat, 10 Oct • 12:00pm - Till late", city: "Johannesburg", lat: -26.2006754, lng: 28.0308807, photo_key: null, photo_url: "https://content.webtickets.co.za/Ritualmediagroup/banner_bttc266_20260324_082209.jpg", color: "#FFB454", description: "Dance the night away with Solo Hoe himself", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1579362846", is_main: true },
  { title: "Fatboy Slim Live in Johannesburg", venue: "James & Ethel Gray Park", cat: "Music", price: "See site for price", date_text: "Sat, 12 Dec · 12:00 PM", city: "Johannesburg", lat: -26.1345, lng: 28.0575, photo_key: null, photo_url: "https://d1as2iufift1z3.cloudfront.net/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89c968a10990ec393e4ab7cd19055248b2a22363/FATBOY26_JHB_HowlerAssets_AG%20WEBSITE%20SIZE.jpeg", color: "#8E7CFF", description: "The Right Here Right Now DJ returns to South Africa for the first time in over 15 years.", source_url: "https://fatboyslim.howler.co.za/events/fatboy-slim-johannesburg-2026-df20" },
  { title: "Jack White Live in Johannesburg", venue: "The Old Park Station, Newtown", cat: "Music", price: "From R1695", date_text: "Fri, 11 Dec • 5:00 PM - 11:00 PM", city: "Johannesburg", lat: -26.1989, lng: 28.0338, photo_key: null, photo_url: "https://etnnn7jauw6.exactdn.com/wp-content/uploads/2026/08/Jack-White.png", color: "#8E7CFF", description: "Grammy-winning rock icon Jack White, formerly of The White Stripes, plays his first-ever Joburg show, presented by BreakOut Events.", source_url: "https://laylo.com/jackwhite/m/JackWhiteLive" },
  { title: "J. Cole — The Fall Off World Tour", venue: "FNB Stadium, Nasrec", cat: "Music", price: "From R715", date_text: "Sat, 12 Dec • 6:00 PM", city: "Johannesburg", lat: -26.2348, lng: 27.9825, photo_key: null, photo_url: "https://etnnn7jauw6.exactdn.com/wp-content/uploads/2026/02/J-Cole-The-Fall-Off-World-Tour-by-David-Peters.png", color: "#FF8080", description: "International rap star J. Cole brings his first solo headline tour in five years to Johannesburg — his only stop on the African continent.", source_url: "https://www.ticketmaster.co.za/event/j-cole-the-fall-off-tour-tickets/628285647" },
  { title: "Halloween 2026: Cape Town", venue: "Castle of Good Hope", cat: "Music", price: "From R349", date_text: "Fri, 30 Oct · 5:00 PM", city: "Cape Town", lat: -33.9273, lng: 18.4297, photo_key: null, photo_url: "https://d1as2iufift1z3.cloudfront.net/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b529b63c7c76910e2d12016b2a583786d66bd70/CT%20FB%20artists%20event%20cover%20copy.jpg", color: "#FF4FA0", description: "Cape Town's biggest Halloween party, with Silverstein, Fokofpolisiekar, Jack Parow and more.", source_url: "https://www.howler.co.za/events/halloween-2026-cape-town-ef15" },
  { title: "R&B Fest — Cape Town", venue: "District", cat: "Music", price: "See site for price", date_text: "Sat, 21 Nov · 9:00 PM", city: "Cape Town", lat: -33.9284462, lng: 18.4240784, photo_key: null, photo_url: "https://fixr-cdn.fixr.co/images/event/2026-07/2e6b8e41c22547efba2ac99eb56ae7ad.jpeg", color: "#33E6C8", description: "An old-school R&B night with DJs spinning 90s and 2000s anthems.", source_url: "https://fixr.co/event/rb-fest-cape-town-tickets-891854911?lang=en-US" },
  { title: "NE-YO Live in South Africa — Cape Town", venue: "Grand Arena, GrandWest", cat: "Music", price: "Sold out — resale via Webtickets", date_text: "Sat, 17 Oct • 6:00 PM", city: "Cape Town", lat: -33.9178, lng: 18.5474, photo_key: null, photo_url: "https://etnnn7jauw6.exactdn.com/wp-content/uploads/2026/06/Neyo-in-South-Africa.png", color: "#FFB454", description: "Grammy-winning R&B hitmaker NE-YO brings his Nights Like This tour to Cape Town, playing hits like 'So Sick' and 'Miss Independent'. Tickets sold out shortly after release.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1596768929" },
  { title: "Halloween — 30 October 2026 (Cabo Beach)", venue: "Cabo Beach Club, V&A Waterfront", cat: "Music", price: "From R350", date_text: "Fri, 30 Oct • 6:00 PM - 2:00 AM", city: "Cape Town", lat: -33.90389, lng: 18.429575, photo_key: null, photo_url: "https://d1as2iufift1z3.cloudfront.net/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ded0826b09229b7057acf3369098c7ed4cd9c71/Halloween%20-%2030%20Oct%2026%20-%20Event%20Cover%20FINAL.png", color: "#FF4FA0", description: "A separate Halloween beach party at Cabo Beach Club (V&A Waterfront), stacked with DBN Gogo, Oscar Mbo, Thakzin and more — not to be confused with the Castle of Good Hope edition.", source_url: "https://ag.howler.co.za/events/halloween-30-october-2026-6488" },
  { title: "A Night With Mthunzi — Durban", venue: "Playhouse Company, Opera Theatre", cat: "Music", price: "R250 - R580 (sold out online)", date_text: "Fri, 30 Oct • 7:30 PM", city: "Durban", lat: -29.858368, lng: 31.026923, photo_key: null, photo_url: "https://content.webtickets.co.za/playhousecompany/banner_Mthunzi_20260716_102811.jpg", color: "#9D7BFF", description: "Amapiano and Afropop star Mthunzi performs his catalogue live with a full band at the Playhouse Opera Theatre, including his hits with Kabza De Small.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1599200828" },
  { title: "Homecoming Africa 2026", venue: "Pretoria National Botanical Gardens", cat: "Music", price: "From R250", date_text: "Sat, 3 Oct • 10:00 AM - 10:00 PM", city: "Pretoria", lat: -25.7389, lng: 28.2721, photo_key: null, photo_url: "https://d1as2iufift1z3.cloudfront.net/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9CQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2ef1a77f0377172d003a8e7de20753ec06554bc/HC26%20-%20MAIN%20ARTWORK%2016X9.png", color: "#FF6F91", description: "A one-day nostalgia festival marking Homecoming Africa's 10th anniversary, themed around 2016-era culture and sound, across multiple stages at the Botanical Gardens.", source_url: "https://www.howler.co.za/HomecomingAfrica2026" },
  { title: "NE-YO Live in South Africa — Pretoria", venue: "Sunbet Arena, Time Square", cat: "Music", price: "From R950", date_text: "Sun, 18 Oct • 6:00 PM", city: "Pretoria", lat: -25.7878, lng: 28.282, photo_key: null, photo_url: "https://etnnn7jauw6.exactdn.com/wp-content/uploads/2026/06/Neyo-in-South-Africa.png", color: "#4FD6C7", description: "Grammy-winning R&B hitmaker NE-YO brings his Nights Like This tour to Pretoria the night after his Cape Town show, performing hits like 'So Sick' and 'Miss Independent'.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1596769068" },
  { title: "Scorpion Kings LIVE", venue: "FNB Stadium, Nasrec", cat: "Music", price: "From R400", date_text: "Sat, 19 Sep • 12:00 PM", city: "Johannesburg", lat: -26.234574, lng: 27.982698, photo_key: null, photo_url: "https://content.webtickets.co.za/SonyMusic/banner_SKSK111_20260820_152843.jpg", color: "#FFD166", description: "DJ Maphorisa and Kabza De Small headline a massive Amapiano celebration at FNB Stadium, following on from a 2025 show that drew over 50,000 fans.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1594173143" },
  { title: "Miguel Live in SA — Pretoria", venue: "Sunbet Arena, Times Square", cat: "Music", price: "From R1190", date_text: "Sun, 23 May 2027 • 6:00 PM", city: "Pretoria", lat: -25.788521, lng: 28.281912, photo_key: null, photo_url: "https://content.webtickets.co.za/VertexEvents/banner_miguelsa1_20260820_080400.jpg", color: "#4CC9F0", description: "Grammy-winning R&B star Miguel plays Pretoria on his three-city South African run, performing favourites like 'Adorn' and 'Sure Thing'.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1600477403" },
  { title: "Maskandi Music Festival", venue: "E'Social Link Shisa Nyama and Car Wash, Soweto", cat: "Music", price: "From R150", date_text: "Sat, 26 Sep • 11:00 AM", city: "Johannesburg", lat: -26.251614, lng: 27.805527, photo_key: null, photo_url: "https://content.webtickets.co.za/MaepaMedia/banner_PHOTOfinal_20260907_103720.jpg", color: "#95E06C", description: "A day-long celebration of Maskandi music at a Soweto shisa nyama venue.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1600004415" },
  { title: "Mr. Duiker Sang the Blues", venue: "Mannie Manim, Market Theatre", cat: "Theatre", price: "From R110", date_text: "Runs 13 Sep - 4 Oct 2026", city: "Johannesburg", lat: -26.201370, lng: 28.032314, photo_key: null, photo_url: "https://content.webtickets.co.za/markettheatre/banner_Mr%20Duiker%20-%20Webtickets%20image%20-%20v2_20260903_115705.jpg", color: "#C77DFF", description: "Dyondzo Kwinika's award-winning stage debut follows a Soweto-born jazz pianist grappling with family history and mental health, adapted from his prize-winning short story.", source_url: "https://www.webtickets.co.za/v2/event.aspx?itemid=1597145329" },
];
